tinyMCE.addI18n('en.paintweb',{
	toolbarButton: 'Edit the selected image in PaintWeb',
  overlayButton: 'Edit',
	contextMenuEdit: 'Edit the image in PaintWeb',
  overlayLoading: 'PaintWeb is loading...',
  statusImageEditing: 'You are editing {file}.',
  statusEditingDataURL: 'You are editing a local data URL.',
  statusSavingDataURL: 'Saving image data URL...',
  statusSavingImage: 'Saving image {file}...',
  statusImageSaved: 'Image save completed successfully!',
  statusImageSaveFailed: 'Image save failed!',
  imageSaveButton: 'Save',
  imageSaveButtonTitle: 'Save the image and return to TinyMCE.',
  cancelButton: 'Cancel',
  cancelButtonTitle: 'Cancel image edits and return to TinyMCE.',
});
