#!/bin/bash
#
# Copyright (c) 2009-2014, Mihai Sucan
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software without
#    specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# $URL: http://code.google.com/p/paintweb $
# $Date: 2014-01-28 12:43:01 $

# This script allows quicker access to the jsdoc-toolkit script.
# Make sure you get the latest jsdoc-toolkit from http://jsdoctoolkit.org/.

shopt -s nullglob

SRC_FOLDER="$1"
DOC_FOLDER="$2"

# Make sure you point to your jsdoc-toolkit package folder.
if [[ -z "$FOLDER_JSDOCT" ]]
then
	FOLDER_JSDOCT="${HOME}/src/jsdoc-toolkit"
fi

JSDOC_JAR="${FOLDER_JSDOCT}/jsrun.jar"
JSDOC_JS="${FOLDER_JSDOCT}/app/run.js"
JSDOC_TEMPLATE="${FOLDER_JSDOCT}/templates/jsdoc"

if [[ ! -d "$SRC_FOLDER" ]]
then
  echo "The source folder does not exist: $SRC_FOLDER"
  exit 1
fi

if [[ ! -d "$FOLDER_JSDOCT" ]]
then
	echo "The jsdoc-toolkit folder does not exist: $FOLDER_JSDOCT"
	exit 1
fi

if [[ ! -f "$JSDOC_JAR" ]]
then
  echo "The jsdoc-toolkit .jar file does not exist!"
  exit 1
fi

if [[ ! -f "$JSDOC_JS" ]]
then
  echo "The jsdoc-toolkit run.js file does not exist!"
  exit 1
fi

if [[ ! -d "$JSDOC_TEMPLATE" ]]
then
  echo "The jsdoc-toolkit template folder does not exist: $JSDOC_TEMPLATE"
  exit 1
fi

mkdir -p "$DOC_FOLDER"

# Simple cleanup
cd "$DOC_FOLDER"
rm *html *css *js
   symbols/*html \
   symbols/*css \
   symbols/*js \
   symbols/src/*html \
   symbols/src/*css \
   symbols/src/*js

cd -

java -jar "$JSDOC_JAR" "$JSDOC_JS" -r=10 -a -p -t=${JSDOC_TEMPLATE} \
     -d=${DOC_FOLDER} "$SRC_FOLDER" -E="json2|debug"

# vim:set spell spl=en fo=wan1croql tw=80 ts=2 sw=2 sts=0 sta noet ai cin fenc=utf-8 ff=unix:

