#!/bin/bash
#
# Copyright (c) 2009-2014, Mihai Sucan
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software without
#    specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# $URL: http://code.google.com/p/paintweb $
# $Date: 2014-01-28 12:46:11 $

# This script allows quicker access to the YUICompressor tool.
# Make sure you get the latest YUICompressor from 
# http://developer.yahoo.com/yui/compressor/

shopt -s nullglob

MY_PWD="$PWD"

# Update this value to point to your yuicompressor folder.
if [[ -z "$FOLDER_YUIC" ]]
then
	FOLDER_YUIC="${HOME}/src/yuicompressor"
fi

if [[ ! -d "$FOLDER_YUIC" ]]
then
	echo "The yuicompressor folder does not exist: $FOLDER_YUIC"
	exit 1
fi

if [[ ! -d "${FOLDER_YUIC}/build" ]]
then
	echo "The yuicompressor build folder does not exist: ${FOLDER_YUIC}/build"
	exit 1
fi

cd "${FOLDER_YUIC}/build"
BIN_YUIC=(*.jar)

if [[ -z "$BIN_YUIC" || ! -f "$BIN_YUIC" ]]
then
	echo "The yuicompressor.jar file was not found!"
	exit 1
fi

cd "$MY_PWD"

java -jar "${FOLDER_YUIC}/build/${BIN_YUIC}" $@

# vim:set spell spl=en fo=wan1croql tw=80 ts=2 sw=2 sts=0 sta noet ai cin fenc=utf-8 ff=unix:

